# Generated by Django 6.1 on 2026-08-07 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Equipo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo_inventario", models.CharField(max_length=30, unique=True)),
                ("nombre", models.CharField(max_length=120)),
                ("categoria", models.CharField(max_length=80)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("disponible", "Disponible"),
                            ("prestado", "Prestado"),
                            ("mantencion", "En mantención"),
                            ("baja", "Dado de baja"),
                        ],
                        default="disponible",
                        max_length=20,
                    ),
                ),
                ("ubicacion", models.CharField(max_length=120)),
                ("cantidad", models.PositiveIntegerField(default=1)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["codigo_inventario"],
            },
        ),
    ]
